/**
 * \mainpage Documentação da IDL
 */
#ifndef __TECGRAF_OPENBUS_CORE_V21_LEGACYSUPPORT_IDL__
#define __TECGRAF_OPENBUS_CORE_V21_LEGACYSUPPORT_IDL__

#include "legacy_access_control.idl"
#include "tecgraf/openbus/core/v2_1/services/access_control.idl"

/** \brief Módulo dos sistemas e aplicações do Tecgraf. */
module tecgraf {

/** \brief Módulo do middleware OpenBus. */
module openbus {

/** \brief Módulo de definições básicas do OpenBus. */
module core {

/* \brief Módulo de versionamento dos Serviços Básicos do OpenBus. */
module v2_1 {

/** \brief Módulo dos Serviços Básicos do OpenBus. */
module services {

/** \brief Módulo com definições de apoio ao suporte legado (OpenBus 2.0). */
module legacy_support {

  interface LegacyConverter {

    v2_0::services::access_control::LoginProcess convertSharedAuth(
      in access_control::LoginProcess attempt)
      raises (UnauthorizedOperation, ServiceFailure);

    v2_0::credential::SignedCallChain convertSignedChain()
      raises (ServiceFailure);

    v2_0::credential::SignedCallChain signChainFor(in Identifier target)
      raises (ServiceFailure);

  };

}; // legacy_support

}; // services

}; // version

}; // core

}; // openbus

}; // tecgraf

#endif
