/**
 * \mainpage Documentação da IDL
 */
#ifndef __TECGRAF_OPENBUS_CORE_V20_DATAEXPORT_IDL__
#define __TECGRAF_OPENBUS_CORE_V20_DATAEXPORT_IDL__

#include "legacy_access_control.idl"

/** \brief Módulo dos sistemas e aplicações do Tecgraf. */
module tecgraf {

/** \brief Módulo do middleware OpenBus. */
module openbus {

/** \brief Módulo de definições básicas do OpenBus. */
module core {

/* \brief Módulo de versionamento dos Serviços Básicos do OpenBus. */
module v2_0 {

/** \brief Módulo com definições de dados exportados usadas para serialização. */
module data_export {

  /** Indicação da versão atual de cofidicação de dados. */
  const unsigned long CurrentVersion = 0x42555300; // 1112888064 "BUS\0";
  /** Indicação da versão legada de cofidicação de dados. */
  const unsigned long LegacyVersion = 1234;
  
  /** Prefixo de streams contendo cadeias de chamadas codificadas. */
  const string MagicTag_CallChain = "BUS\x01";
  /** Prefixo de streams contendo informações de autenticação compartilhada. */
  const string MagicTag_SharedAuth = "BUS\x02";

  /**
   * \brief Estrutura utilizada para exportar dados versionados de forma
   *        interoperável para um stream de bytes.
   */
  struct ExportedVersion {
    /** Indicação da versão da codificação do dado. */
    unsigned long version;
    /** Codificação do dado no formado indicado pela versão. */
    OctetSeq encoded;
  };
  typedef sequence<ExportedVersion> ExportedVersionSeq;
  
  /**
   * \brief Estrutura utilizada para exportar uma cadeia de chamadas para um
   *        stream de bytes.
   */
  struct ExportedCallChain {
    /** \brief UUID do barramento ao qual a cadeia está associada. */
    Identifier bus;
    /** \brief Cadeia de chamadas aninhadas da requisição. */
    credential::SignedCallChain signedChain;
  };
  
  /**
   * \brief Estrutura utilizada para exportar uma cadeia de chamadas contendo
   *        dados obitidos de uma chamada legada para um stream de bytes.
   */
  struct LegacyExportedCallChain {
    /** \brief UUID do barramento ao qual a cadeia está associada. */
    Identifier bus;
    /** \brief Identificador da entidade que recebeu a chamada. */
    Identifier target;
    /** \brief Informações de login que efetivamente fez a chamada. */
    services::access_control::LoginInfo caller;
    /** \brief Identificador da entidade que originou a chamada. */
    Identifier delegate;
  };
  
  /**
   * \brief Estrutura utilizada para exportar informações de autenticação
   *        compartilhada para um stream de bytes
   */
  struct ExportedSharedAuth {
    /** \brief UUID do barramento ao qual a cadeia está associada */
    Identifier bus;
    /** Objeto a ser usado para efetuar o login. */
    services::access_control::LoginProcess attempt;
    /** Segredo a ser usado para efetuar o login. */
    OctetSeq secret;
  };

}; // data_export

}; // version

}; // core

}; // openbus

}; // tecgraf

#endif
