/**
 * \mainpage Documentação da IDL
 */
#ifndef __TECGRAF_OPENBUS_CORE_V20_CREDENTIAL_IDL__
#define __TECGRAF_OPENBUS_CORE_V20_CREDENTIAL_IDL__

#include "legacy_core.idl"

/** \brief Módulo dos sistemas e aplicações do Tecgraf. */
module tecgraf {

/** \brief Módulo do middleware OpenBus. */
module openbus {

/** \brief Módulo de definições básicas do OpenBus. */
module core {

/* \brief Módulo de versionamento dos Serviços Básicos do OpenBus. */
module v2_0 {

/** \brief Módulo com definições de credenciais usadas para autenticação. */
module credential {
  
  /** 
   * \brief Identificador de contexto do service context utilizado para 
   * transmitir a credencial 
   */
  const unsigned long CredentialContextId = 0x42555300; // 1112888064 "BUS\0"
  
  /**
   * \brief Estrutura que possui a cadeia de chamadas aninhadas da requisição
   */
  struct SignedCallChain {
    EncryptedBlock signature; /**< \brief Hash de 'encoded' assinado pelo barramento. */
    OctetSeq encoded; /**< \brief estrutura services::access_control::CallChain codificada usando CDR */
  };
  
  /**
   * \brief Estrutura trafegada durante as comunicações realizadas dentro do 
   * barramento, que assegura a identidade da entidade que iniciou a chamada.
   */
  struct CredentialData {
    Identifier bus; /**< \brief UUID do barramento */
    Identifier login; /**< \brief UUID de quem inicia a comunicação (requisitante)*/
    unsigned long session; /**< \brief Identificador da sessão */
    unsigned long ticket; /**< \brief Contado crescente e monotômico */
    HashValue hash; /**< \brief Hash SHA-256 de:  versão do protocolo + valor aleatório de 16-bytes + ticket + operation_name*/
    SignedCallChain chain; /**< \brief Cadeia de chamadas assinada */
  };
  
  /**
   * \brief Estrutura trafegada para combinar uma sessão para a realização de 
   * uma comunicação dentro do barramento
   */
  struct CredentialReset {
    Identifier target; /**< \brief UUID do alvo da comunicação (receptor)*/
    unsigned long session; /**< \brief Identificador da sessão */
    EncryptedBlock challenge; /**< \brief Valor aleatório de 16-bytes encriptado */
  };
  
}; // credentials

}; // version

}; // core

}; // openbus

}; // tecgraf

#endif
